supervisor:
  name: TaskManager
  type: supervisor
  llm_config:
    model: ${LLM_MODEL}
    api_key: ${LLM_API_KEY}
    base_url: ${LLM_BASE_URL}
  system_message: "You are the task management supervisor. Remember, the user can only see your message, so provide complete information from the agent's/supervisors message as well."
  children:
    - name: TaskCreator
      type: agent
      llm_config:
        model: ${LLM_MODEL}
        api_key: ${LLM_API_KEY}
        base_url: ${LLM_BASE_URL}
      system_message: "You are responsible for creating new tasks."
      tools:
        - name: add_task
          type: function
          python_path: examples.task_management_with_yaml.task_tools.add_task
          description: "Add a new task to the list"
          parameters:
            task:
              type: string
              description: "The task to be added"
    - name: TaskOrganizer
      type: supervisor
      llm_config:
        model: ${LLM_MODEL}
        api_key: ${LLM_API_KEY}
        base_url: ${LLM_BASE_URL}
      system_message: "You are a sub-supervisor managing task listing and prioritization. Remember, the user can only see your message, so provide complete information from the agent's message as well."
      children:
        - name: TaskLister
          type: agent
          llm_config:
            model: ${LLM_MODEL}
            api_key: ${LLM_API_KEY}
            base_url: ${LLM_BASE_URL}
          system_message: "You are responsible for listing tasks."
          tools:
            - name: list_tasks
              type: function
              python_path: examples.task_management_with_yaml.task_tools.list_tasks
              description: "List all current tasks"
        - name: PriorityCalculator
          type: agent
          llm_config:
            model: ${LLM_MODEL}
            api_key: ${LLM_API_KEY}
            base_url: ${LLM_BASE_URL}
          system_message: "You calculate the priority of tasks based on urgency and importance."
          tools:
            - name: calculate_priority
              type: function
              python_path: examples.task_management_with_yaml.task_tools.calculate_priority
              description: "Calculate the priority of a task"
              parameters:
                urgency:
                  type: integer
                  description: "The urgency of the task (1-10)"
                importance:
                  type: integer
                  description: "The importance of the task (1-10)"